import type { WorkloadPreset } from "./types";

// Starting assumptions for the UX, not claims about every system in a category.
export const PRESETS: WorkloadPreset[] = [
  {
    id: "drone",
    name: "Drone",
    unitLabel: "Drones",
    units: 10,
    recordingHoursPerDay: 2,
    streams: [
      {
        id: "drone-0",
        name: "Camera",
        enabled: true,
        count: 1,
        frequencyHz: 10,
        recordSizeKb: 200,
      },
      {
        id: "drone-1",
        name: "LiDAR",
        enabled: true,
        count: 1,
        frequencyHz: 10,
        recordSizeKb: 1000,
      },
      {
        id: "drone-2",
        name: "Telemetry",
        enabled: true,
        count: 1,
        frequencyHz: 100,
        recordSizeKb: 1,
      },
      {
        id: "drone-3",
        name: "IMU",
        enabled: true,
        count: 1,
        frequencyHz: 200,
        recordSizeKb: 0.5,
      },
      {
        id: "drone-4",
        name: "Logs",
        enabled: true,
        count: 1,
        frequencyHz: 5,
        recordSizeKb: 4,
      },
    ],
  },
  {
    id: "mobile-robot",
    name: "Mobile robot",
    unitLabel: "Mobile robots",
    units: 5,
    recordingHoursPerDay: 8,
    streams: [
      {
        id: "mobile-robot-0",
        name: "Cameras",
        enabled: true,
        count: 2,
        frequencyHz: 10,
        recordSizeKb: 150,
      },
      {
        id: "mobile-robot-1",
        name: "LiDAR",
        enabled: true,
        count: 1,
        frequencyHz: 10,
        recordSizeKb: 1000,
      },
      {
        id: "mobile-robot-2",
        name: "Telemetry",
        enabled: true,
        count: 1,
        frequencyHz: 100,
        recordSizeKb: 2,
      },
      {
        id: "mobile-robot-3",
        name: "IMU",
        enabled: true,
        count: 1,
        frequencyHz: 100,
        recordSizeKb: 1,
      },
      {
        id: "mobile-robot-4",
        name: "Logs",
        enabled: true,
        count: 1,
        frequencyHz: 10,
        recordSizeKb: 5,
      },
    ],
  },
  {
    id: "autonomous-vehicle",
    name: "Autonomous vehicle",
    unitLabel: "Vehicles",
    units: 2,
    recordingHoursPerDay: 8,
    streams: [
      {
        id: "autonomous-vehicle-0",
        name: "Cameras",
        enabled: true,
        count: 6,
        frequencyHz: 10,
        recordSizeKb: 250,
      },
      {
        id: "autonomous-vehicle-1",
        name: "LiDAR",
        enabled: true,
        count: 2,
        frequencyHz: 10,
        recordSizeKb: 2000,
      },
      {
        id: "autonomous-vehicle-2",
        name: "Radar",
        enabled: true,
        count: 4,
        frequencyHz: 20,
        recordSizeKb: 50,
      },
      {
        id: "autonomous-vehicle-3",
        name: "CAN / telemetry",
        enabled: true,
        count: 1,
        frequencyHz: 200,
        recordSizeKb: 2,
      },
      {
        id: "autonomous-vehicle-4",
        name: "Logs",
        enabled: true,
        count: 1,
        frequencyHz: 20,
        recordSizeKb: 5,
      },
    ],
  },
  {
    id: "industrial-robot",
    name: "Industrial robot",
    unitLabel: "Industrial robots",
    units: 25,
    recordingHoursPerDay: 16,
    streams: [
      {
        id: "industrial-robot-0",
        name: "Camera",
        enabled: true,
        count: 1,
        frequencyHz: 5,
        recordSizeKb: 200,
      },
      {
        id: "industrial-robot-1",
        name: "Joint telemetry",
        enabled: true,
        count: 1,
        frequencyHz: 250,
        recordSizeKb: 2,
      },
      {
        id: "industrial-robot-2",
        name: "Force / torque",
        enabled: true,
        count: 1,
        frequencyHz: 100,
        recordSizeKb: 2,
      },
      {
        id: "industrial-robot-3",
        name: "PLC data",
        enabled: true,
        count: 1,
        frequencyHz: 20,
        recordSizeKb: 2,
      },
      {
        id: "industrial-robot-4",
        name: "Logs",
        enabled: true,
        count: 1,
        frequencyHz: 10,
        recordSizeKb: 5,
      },
    ],
  },
  {
    id: "computer-vision",
    name: "Computer vision",
    unitLabel: "Cameras",
    units: 20,
    recordingHoursPerDay: 24,
    streams: [
      {
        id: "computer-vision-0",
        name: "Images",
        enabled: true,
        count: 1,
        frequencyHz: 2,
        recordSizeKb: 500,
      },
      {
        id: "computer-vision-1",
        name: "Detection metadata",
        enabled: true,
        count: 1,
        frequencyHz: 2,
        recordSizeKb: 5,
      },
      {
        id: "computer-vision-2",
        name: "Events",
        enabled: true,
        count: 1,
        frequencyHz: 0.2,
        recordSizeKb: 5,
      },
      {
        id: "computer-vision-3",
        name: "Diagnostics",
        enabled: true,
        count: 1,
        frequencyHz: 0.2,
        recordSizeKb: 2,
      },
    ],
  },
  {
    id: "vibration",
    name: "Vibration data",
    unitLabel: "Machines",
    units: 100,
    recordingHoursPerDay: 24,
    streams: [
      {
        id: "vibration-0",
        name: "Vibration windows",
        enabled: true,
        count: 4,
        frequencyHz: 1,
        recordSizeKb: 64,
      },
      {
        id: "vibration-1",
        name: "Machine telemetry",
        enabled: true,
        count: 1,
        frequencyHz: 10,
        recordSizeKb: 2,
      },
      {
        id: "vibration-2",
        name: "Condition metrics",
        enabled: true,
        count: 1,
        frequencyHz: 1,
        recordSizeKb: 2,
      },
      {
        id: "vibration-3",
        name: "Events",
        enabled: true,
        count: 1,
        frequencyHz: 0.05,
        recordSizeKb: 5,
      },
    ],
  },
  {
    id: "plc",
    name: "PLC & telemetry",
    unitLabel: "PLCs",
    units: 100,
    recordingHoursPerDay: 24,
    streams: [
      {
        id: "plc-0",
        name: "Process telemetry",
        enabled: true,
        count: 1,
        frequencyHz: 10,
        recordSizeKb: 2,
      },
      {
        id: "plc-1",
        name: "Fast signals",
        enabled: true,
        count: 1,
        frequencyHz: 100,
        recordSizeKb: 1,
      },
      {
        id: "plc-2",
        name: "Events",
        enabled: true,
        count: 1,
        frequencyHz: 0.2,
        recordSizeKb: 2,
      },
      {
        id: "plc-3",
        name: "Logs",
        enabled: true,
        count: 1,
        frequencyHz: 1,
        recordSizeKb: 4,
      },
    ],
  },
  {
    id: "machine-vision-qa",
    name: "Machine vision QA",
    unitLabel: "Stations",
    units: 25,
    recordingHoursPerDay: 16,
    streams: [
      {
        id: "machine-vision-qa-0",
        name: "Inspection images",
        enabled: true,
        count: 2,
        frequencyHz: 1,
        recordSizeKb: 2000,
      },
      {
        id: "machine-vision-qa-1",
        name: "Detection results",
        enabled: true,
        count: 1,
        frequencyHz: 1,
        recordSizeKb: 10,
      },
      {
        id: "machine-vision-qa-2",
        name: "PLC context",
        enabled: true,
        count: 1,
        frequencyHz: 10,
        recordSizeKb: 2,
      },
      {
        id: "machine-vision-qa-3",
        name: "Rejected sample",
        enabled: false,
        count: 1,
        frequencyHz: 0.05,
        recordSizeKb: 5000,
      },
    ],
  },
  {
    id: "ros",
    name: "ROS / research",
    unitLabel: "Robots",
    units: 10,
    recordingHoursPerDay: 4,
    streams: [
      {
        id: "ros-0",
        name: "Camera topics",
        enabled: true,
        count: 2,
        frequencyHz: 10,
        recordSizeKb: 200,
      },
      {
        id: "ros-1",
        name: "Point clouds",
        enabled: true,
        count: 1,
        frequencyHz: 5,
        recordSizeKb: 1000,
      },
      {
        id: "ros-2",
        name: "ROS telemetry",
        enabled: true,
        count: 1,
        frequencyHz: 100,
        recordSizeKb: 2,
      },
      {
        id: "ros-3",
        name: "TF / poses",
        enabled: true,
        count: 1,
        frequencyHz: 50,
        recordSizeKb: 1,
      },
      {
        id: "ros-4",
        name: "Logs",
        enabled: true,
        count: 1,
        frequencyHz: 10,
        recordSizeKb: 5,
      },
    ],
  },
  {
    id: "custom",
    name: "Custom",
    unitLabel: "Data sources",
    units: 10,
    recordingHoursPerDay: 8,
    streams: [
      {
        id: "custom-0",
        name: "Stream 1",
        enabled: true,
        count: 1,
        frequencyHz: 10,
        recordSizeKb: 100,
      },
      {
        id: "custom-1",
        name: "Stream 2",
        enabled: false,
        count: 1,
        frequencyHz: 10,
        recordSizeKb: 10,
      },
      {
        id: "custom-2",
        name: "Stream 3",
        enabled: false,
        count: 1,
        frequencyHz: 1,
        recordSizeKb: 1,
      },
      {
        id: "custom-3",
        name: "Stream 4",
        enabled: false,
        count: 1,
        frequencyHz: 1,
        recordSizeKb: 1,
      },
      {
        id: "custom-4",
        name: "Stream 5",
        enabled: false,
        count: 1,
        frequencyHz: 1,
        recordSizeKb: 1,
      },
    ],
  },
];
