import type { WorkloadPreset } from "./types";

// Starting assumptions for the UX, not claims about every system in a category.
export const PRESETS: WorkloadPreset[] = [
  {
    id: "mobile-robot",
    name: "Mobile robot",
    unitLabel: "Mobile robots",
    units: 10,
    recordingHoursPerDay: 8,
    hotDays: 30,
    retentionDays: 90,
    streams: [
      {
        id: "mobile-robot-0",
        dataClass: "blob",
        name: "Cameras",
        enabled: true,
        count: 2,
        frequencyHz: 10,
        recordSizeKb: 150,
      },
      {
        id: "mobile-robot-1",
        dataClass: "blob",
        name: "LiDAR",
        enabled: true,
        count: 1,
        frequencyHz: 10,
        recordSizeKb: 1000,
      },
      {
        id: "mobile-robot-2",
        dataClass: "metric",
        name: "Telemetry",
        enabled: true,
        count: 1,
        frequencyHz: 100,
        recordSizeKb: 2,
      },
      {
        id: "mobile-robot-3",
        dataClass: "metric",
        name: "IMU",
        enabled: true,
        count: 1,
        frequencyHz: 100,
        recordSizeKb: 1,
      },
      {
        id: "mobile-robot-4",
        dataClass: "log",
        name: "Logs",
        enabled: true,
        count: 1,
        frequencyHz: 10,
        recordSizeKb: 5,
      },
    ],
  },
  {
    id: "autonomous-vehicle",
    name: "Autonomous vehicle",
    unitLabel: "Vehicles",
    units: 10,
    recordingHoursPerDay: 8,
    hotDays: 30,
    retentionDays: 30,
    streams: [
      {
        id: "autonomous-vehicle-0",
        dataClass: "blob",
        name: "Cameras",
        enabled: true,
        count: 6,
        frequencyHz: 10,
        recordSizeKb: 250,
      },
      {
        id: "autonomous-vehicle-1",
        dataClass: "blob",
        name: "LiDAR",
        enabled: true,
        count: 2,
        frequencyHz: 10,
        recordSizeKb: 2000,
      },
      {
        id: "autonomous-vehicle-2",
        dataClass: "blob",
        name: "Radar",
        enabled: true,
        count: 4,
        frequencyHz: 20,
        recordSizeKb: 50,
      },
      {
        id: "autonomous-vehicle-3",
        dataClass: "metric",
        name: "CAN / telemetry",
        enabled: true,
        count: 1,
        frequencyHz: 200,
        recordSizeKb: 2,
      },
      {
        id: "autonomous-vehicle-4",
        dataClass: "log",
        name: "Logs",
        enabled: true,
        count: 1,
        frequencyHz: 20,
        recordSizeKb: 5,
      },
    ],
  },
  {
    id: "drone",
    name: "Drone",
    unitLabel: "Drones",
    units: 10,
    recordingHoursPerDay: 4,
    hotDays: 30,
    retentionDays: 120,
    streams: [
      {
        id: "drone-0",
        dataClass: "blob",
        name: "Camera",
        enabled: true,
        count: 1,
        frequencyHz: 10,
        recordSizeKb: 200,
      },
      {
        id: "drone-1",
        dataClass: "blob",
        name: "LiDAR",
        enabled: true,
        count: 1,
        frequencyHz: 10,
        recordSizeKb: 1000,
      },
      {
        id: "drone-2",
        dataClass: "metric",
        name: "Telemetry",
        enabled: true,
        count: 1,
        frequencyHz: 100,
        recordSizeKb: 1,
      },
      {
        id: "drone-3",
        dataClass: "metric",
        name: "IMU",
        enabled: true,
        count: 1,
        frequencyHz: 200,
        recordSizeKb: 0.5,
      },
      {
        id: "drone-4",
        dataClass: "log",
        name: "Logs",
        enabled: true,
        count: 1,
        frequencyHz: 5,
        recordSizeKb: 4,
      },
    ],
  },
  {
    id: "industrial-robot",
    name: "Industrial robot",
    unitLabel: "Industrial robots",
    units: 25,
    recordingHoursPerDay: 16,
    hotDays: 30,
    retentionDays: 90,
    streams: [
      {
        id: "industrial-robot-0",
        dataClass: "blob",
        name: "Camera",
        enabled: true,
        count: 1,
        frequencyHz: 5,
        recordSizeKb: 200,
      },
      {
        id: "industrial-robot-1",
        dataClass: "metric",
        name: "Joint telemetry",
        enabled: true,
        count: 1,
        frequencyHz: 250,
        recordSizeKb: 2,
      },
      {
        id: "industrial-robot-2",
        dataClass: "metric",
        name: "Force / torque",
        enabled: true,
        count: 1,
        frequencyHz: 100,
        recordSizeKb: 2,
      },
      {
        id: "industrial-robot-3",
        dataClass: "metric",
        name: "PLC data",
        enabled: true,
        count: 1,
        frequencyHz: 20,
        recordSizeKb: 2,
      },
      {
        id: "industrial-robot-4",
        dataClass: "log",
        name: "Logs",
        enabled: true,
        count: 1,
        frequencyHz: 10,
        recordSizeKb: 5,
      },
    ],
  },
];
